# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end
  
  lane :build_and_distribute do
    increment_vc()
    build()
    distribute_to_firebase()
  end
  
  desc "Increment version code"
  private_lane :increment_vc do
  increment_version_code(
       gradle_file_path: "./app/build.gradle",

  )
  end
  
  desc "Build the .apk file"
  private_lane :build do
  gradle(
    task: "clean assemble",
    build_type: ENV['BUILD_TYPE'],
	properties: {
    "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
    "android.injected.signing.store.password" => ENV['KEYSTORE_PASS'],
    "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
    "android.injected.signing.key.password" => ENV['KEY_PASS'],
    }
  )
  end
  
  desc "Lane for distributing app using Firebase App Distributions"
  private_lane :distribute_to_firebase do
    firebase_app_distribution(
	        service_credentials_file: "firebase_credentials.json",
            app: ENV['FIREBASE_APP_ID'],
            release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
            groups_file: "FirebaseAppDistributionConfig/groups.txt"
        )
  end

end
